[2021-11-25 23:44:36.838] ERROR [4660821440] - {"req_id": "DJEHWG20211125234436", "http_method": "POST", "url_path": "/payment/payment_checkout", "headers": [["host", "0.0.0.0:8888"], ["connection", "keep-alive"], ["content-length", "412"], ["accept", "application/json"], ["dnt", "1"], ["user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36"], ["content-type", "application/json"], ["origin", "http://0.0.0.0:8888"], ["referer", "http://0.0.0.0:8888/docs"], ["accept-encoding", "gzip, deflate"], ["accept-language", "en-US,en;q=0.9,id;q=0.8,ms;q=0.7"]], "query_param": [], "ip_forwarded": null, "ip_client_host": "127.0.0.1", "request_body": "{\n  \"invoice_no\": \"spaj/10202/1010\",\n  \"total_amount\": \"30000\",\n  \"customer\": {\n    \"custid\": \"CUST-0001\",\n    \"name\": \"Anton Budiman\",\n    \"email\": \"anton@example.com\",\n    \"phone\": \"6285694566147\",\n    \"address\": \"Menara Mulia Lantai 8\"\n  },\n  \"line_items\": [\n    {\n      \"name\": \"Asuransi\",\n      \"price\": \"30000\",\n      \"qty\": \"1\"\n    }\n  ],\n  \"paytype\": \"string\",\n  \"payvendor\": \"Doku\",\n  \"bank\": \"string\"\n}", "error": "Object of type Items is not JSON serializable", "trace": "[FrameInfo(frame=<frame at 0x7f98dec952f0, file './routers/__init__.py', line 69, code custom_route_handler>, filename='./routers/__init__.py', lineno=45, function='custom_route_handler', code_context=['                response: Response = await original_route_handler(request)\\n'], index=0), FrameInfo(frame=<frame at 0x7f98dee2ed20, file '/usr/local/lib/python3.8/site-packages/fastapi/routing.py', line 226, code app>, filename='/usr/local/lib/python3.8/site-packages/fastapi/routing.py', lineno=226, function='app', code_context=['            raw_response = await run_endpoint_function(\\n'], index=0), FrameInfo(frame=<frame at 0x111de41f0, file '/usr/local/lib/python3.8/site-packages/fastapi/routing.py', line 161, code run_endpoint_function>, filename='/usr/local/lib/python3.8/site-packages/fastapi/routing.py', lineno=161, function='run_endpoint_function', code_context=['        return await run_in_threadpool(dependant.call, **values)\\n'], index=0), FrameInfo(frame=<frame at 0x111dd5b20, file '/usr/local/lib/python3.8/site-packages/starlette/concurrency.py', line 40, code run_in_threadpool>, filename='/usr/local/lib/python3.8/site-packages/starlette/concurrency.py', lineno=40, function='run_in_threadpool', code_context=['    return await loop.run_in_executor(None, func, *args)\\n'], index=0), FrameInfo(frame=<frame at 0x111e0a040, file '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py', line 63, code run>, filename='/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py', lineno=57, function='run', code_context=['            result = self.fn(*self.args, **self.kwargs)\\n'], index=0), FrameInfo(frame=<frame at 0x7f98dee2f420, file './routers/payment.py', line 56, code payment_checkout>, filename='./routers/payment.py', lineno=56, function='payment_checkout', code_context=['    digest = hlp.genDigest(json.dumps(args))\\n'], index=0), FrameInfo(frame=<frame at 0x7f98dec93aa0, file '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py', line 231, code dumps>, filename='/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py', lineno=231, function='dumps', code_context=['        return _default_encoder.encode(obj)\\n'], index=0), FrameInfo(frame=<frame at 0x7f98dec94580, file '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', line 199, code encode>, filename='/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', lineno=199, function='encode', code_context=['        chunks = self.iterencode(o, _one_shot=True)\\n'], index=0), FrameInfo(frame=<frame at 0x7f98dec94020, file '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', line 257, code iterencode>, filename='/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', lineno=257, function='iterencode', code_context=['        return _iterencode(o, 0)\\n'], index=0), FrameInfo(frame=<frame at 0x111dbfc10, file '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', line 179, code default>, filename='/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', lineno=179, function='default', code_context=[\"        raise TypeError(f'Object of type {o.__class__.__name__} '\\n\"], index=0)]"}
Traceback (most recent call last):
  File "./routers/__init__.py", line 45, in custom_route_handler
    response: Response = await original_route_handler(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./routers/payment.py", line 56, in payment_checkout
    digest = hlp.genDigest(json.dumps(args))
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Items is not JSON serializable
[2021-11-25 23:46:58.330] ERROR [4561599936] - {"req_id": "05WZWS20211125234658", "http_method": "POST", "url_path": "/payment/payment_checkout", "headers": [["host", "0.0.0.0:8888"], ["connection", "keep-alive"], ["content-length", "412"], ["accept", "application/json"], ["dnt", "1"], ["user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36"], ["content-type", "application/json"], ["origin", "http://0.0.0.0:8888"], ["referer", "http://0.0.0.0:8888/docs"], ["accept-encoding", "gzip, deflate"], ["accept-language", "en-US,en;q=0.9,id;q=0.8,ms;q=0.7"]], "query_param": [], "ip_forwarded": null, "ip_client_host": "127.0.0.1", "request_body": "{\n  \"invoice_no\": \"spaj/10202/1010\",\n  \"total_amount\": \"30000\",\n  \"customer\": {\n    \"custid\": \"CUST-0001\",\n    \"name\": \"Anton Budiman\",\n    \"email\": \"anton@example.com\",\n    \"phone\": \"6285694566147\",\n    \"address\": \"Menara Mulia Lantai 8\"\n  },\n  \"line_items\": [\n    {\n      \"name\": \"Asuransi\",\n      \"price\": \"30000\",\n      \"qty\": \"1\"\n    }\n  ],\n  \"paytype\": \"string\",\n  \"payvendor\": \"Doku\",\n  \"bank\": \"string\"\n}", "error": "Object of type Items is not JSON serializable", "trace": "[FrameInfo(frame=<frame at 0x7f7f5286a4f0, file './routers/__init__.py', line 69, code custom_route_handler>, filename='./routers/__init__.py', lineno=45, function='custom_route_handler', code_context=['                response: Response = await original_route_handler(request)\\n'], index=0), FrameInfo(frame=<frame at 0x7f7f514c6c00, file '/usr/local/lib/python3.8/site-packages/fastapi/routing.py', line 226, code app>, filename='/usr/local/lib/python3.8/site-packages/fastapi/routing.py', lineno=226, function='app', code_context=['            raw_response = await run_endpoint_function(\\n'], index=0), FrameInfo(frame=<frame at 0x1099613a0, file '/usr/local/lib/python3.8/site-packages/fastapi/routing.py', line 161, code run_endpoint_function>, filename='/usr/local/lib/python3.8/site-packages/fastapi/routing.py', lineno=161, function='run_endpoint_function', code_context=['        return await run_in_threadpool(dependant.call, **values)\\n'], index=0), FrameInfo(frame=<frame at 0x10995cb20, file '/usr/local/lib/python3.8/site-packages/starlette/concurrency.py', line 40, code run_in_threadpool>, filename='/usr/local/lib/python3.8/site-packages/starlette/concurrency.py', lineno=40, function='run_in_threadpool', code_context=['    return await loop.run_in_executor(None, func, *args)\\n'], index=0), FrameInfo(frame=<frame at 0x109964230, file '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py', line 63, code run>, filename='/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py', lineno=57, function='run', code_context=['            result = self.fn(*self.args, **self.kwargs)\\n'], index=0), FrameInfo(frame=<frame at 0x7f7f52a83260, file './routers/payment.py', line 57, code payment_checkout>, filename='./routers/payment.py', lineno=57, function='payment_checkout', code_context=['    digest = hlp.genDigest(json.dumps(args))\\n'], index=0), FrameInfo(frame=<frame at 0x7f7f52a834e0, file '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py', line 231, code dumps>, filename='/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py', lineno=231, function='dumps', code_context=['        return _default_encoder.encode(obj)\\n'], index=0), FrameInfo(frame=<frame at 0x10995ec80, file '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', line 199, code encode>, filename='/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', lineno=199, function='encode', code_context=['        chunks = self.iterencode(o, _one_shot=True)\\n'], index=0), FrameInfo(frame=<frame at 0x7f7f52a83710, file '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', line 257, code iterencode>, filename='/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', lineno=257, function='iterencode', code_context=['        return _iterencode(o, 0)\\n'], index=0), FrameInfo(frame=<frame at 0x109961700, file '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', line 179, code default>, filename='/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', lineno=179, function='default', code_context=[\"        raise TypeError(f'Object of type {o.__class__.__name__} '\\n\"], index=0)]"}
Traceback (most recent call last):
  File "./routers/__init__.py", line 45, in custom_route_handler
    response: Response = await original_route_handler(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./routers/payment.py", line 57, in payment_checkout
    digest = hlp.genDigest(json.dumps(args))
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Items is not JSON serializable
[2021-11-25 23:49:07.886] ERROR [4561599936] - {"req_id": "ZX4R0C20211125234907", "http_method": "POST", "url_path": "/payment/payment_checkout", "headers": [["host", "0.0.0.0:8888"], ["connection", "keep-alive"], ["content-length", "412"], ["accept", "application/json"], ["dnt", "1"], ["user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36"], ["content-type", "application/json"], ["origin", "http://0.0.0.0:8888"], ["referer", "http://0.0.0.0:8888/docs"], ["accept-encoding", "gzip, deflate"], ["accept-language", "en-US,en;q=0.9,id;q=0.8,ms;q=0.7"]], "query_param": [], "ip_forwarded": null, "ip_client_host": "127.0.0.1", "request_body": "{\n  \"invoice_no\": \"spaj/10202/1010\",\n  \"total_amount\": \"30000\",\n  \"customer\": {\n    \"custid\": \"CUST-0001\",\n    \"name\": \"Anton Budiman\",\n    \"email\": \"anton@example.com\",\n    \"phone\": \"6285694566147\",\n    \"address\": \"Menara Mulia Lantai 8\"\n  },\n  \"line_items\": [\n    {\n      \"name\": \"Asuransi\",\n      \"price\": \"30000\",\n      \"qty\": \"1\"\n    }\n  ],\n  \"paytype\": \"string\",\n  \"payvendor\": \"Doku\",\n  \"bank\": \"string\"\n}", "error": "Object of type Items is not JSON serializable", "trace": "[FrameInfo(frame=<frame at 0x7f7f5286a4f0, file './routers/__init__.py', line 69, code custom_route_handler>, filename='./routers/__init__.py', lineno=45, function='custom_route_handler', code_context=['                response: Response = await original_route_handler(request)\\n'], index=0), FrameInfo(frame=<frame at 0x7f7f514c6c00, file '/usr/local/lib/python3.8/site-packages/fastapi/routing.py', line 226, code app>, filename='/usr/local/lib/python3.8/site-packages/fastapi/routing.py', lineno=226, function='app', code_context=['            raw_response = await run_endpoint_function(\\n'], index=0), FrameInfo(frame=<frame at 0x1099613a0, file '/usr/local/lib/python3.8/site-packages/fastapi/routing.py', line 161, code run_endpoint_function>, filename='/usr/local/lib/python3.8/site-packages/fastapi/routing.py', lineno=161, function='run_endpoint_function', code_context=['        return await run_in_threadpool(dependant.call, **values)\\n'], index=0), FrameInfo(frame=<frame at 0x10995cb20, file '/usr/local/lib/python3.8/site-packages/starlette/concurrency.py', line 40, code run_in_threadpool>, filename='/usr/local/lib/python3.8/site-packages/starlette/concurrency.py', lineno=40, function='run_in_threadpool', code_context=['    return await loop.run_in_executor(None, func, *args)\\n'], index=0), FrameInfo(frame=<frame at 0x109964230, file '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py', line 63, code run>, filename='/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py', lineno=57, function='run', code_context=['            result = self.fn(*self.args, **self.kwargs)\\n'], index=0), FrameInfo(frame=<frame at 0x7f7f52a83260, file './routers/payment.py', line 57, code payment_checkout>, filename='./routers/payment.py', lineno=57, function='payment_checkout', code_context=['    digest = hlp.genDigest(json.dumps(args))\\n'], index=0), FrameInfo(frame=<frame at 0x7f7f514c75d0, file '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py', line 231, code dumps>, filename='/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py', lineno=231, function='dumps', code_context=['        return _default_encoder.encode(obj)\\n'], index=0), FrameInfo(frame=<frame at 0x10996ac80, file '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', line 199, code encode>, filename='/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', lineno=199, function='encode', code_context=['        chunks = self.iterencode(o, _one_shot=True)\\n'], index=0), FrameInfo(frame=<frame at 0x7f7f52a83920, file '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', line 257, code iterencode>, filename='/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', lineno=257, function='iterencode', code_context=['        return _iterencode(o, 0)\\n'], index=0), FrameInfo(frame=<frame at 0x109961700, file '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', line 179, code default>, filename='/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', lineno=179, function='default', code_context=[\"        raise TypeError(f'Object of type {o.__class__.__name__} '\\n\"], index=0)]"}
Traceback (most recent call last):
  File "./routers/__init__.py", line 45, in custom_route_handler
    response: Response = await original_route_handler(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./routers/payment.py", line 57, in payment_checkout
    digest = hlp.genDigest(json.dumps(args))
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Items is not JSON serializable
[2021-11-25 23:51:56.717] ERROR [4692483520] - {"req_id": "MNGGNF20211125235156", "http_method": "POST", "url_path": "/payment/payment_checkout", "headers": [["host", "0.0.0.0:8888"], ["connection", "keep-alive"], ["content-length", "412"], ["accept", "application/json"], ["dnt", "1"], ["user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36"], ["content-type", "application/json"], ["origin", "http://0.0.0.0:8888"], ["referer", "http://0.0.0.0:8888/docs"], ["accept-encoding", "gzip, deflate"], ["accept-language", "en-US,en;q=0.9,id;q=0.8,ms;q=0.7"]], "query_param": [], "ip_forwarded": null, "ip_client_host": "127.0.0.1", "request_body": "{\n  \"invoice_no\": \"spaj/10202/1010\",\n  \"total_amount\": \"30000\",\n  \"customer\": {\n    \"custid\": \"CUST-0001\",\n    \"name\": \"Anton Budiman\",\n    \"email\": \"anton@example.com\",\n    \"phone\": \"6285694566147\",\n    \"address\": \"Menara Mulia Lantai 8\"\n  },\n  \"line_items\": [\n    {\n      \"name\": \"Asuransi\",\n      \"price\": \"30000\",\n      \"qty\": \"1\"\n    }\n  ],\n  \"paytype\": \"string\",\n  \"payvendor\": \"Doku\",\n  \"bank\": \"string\"\n}", "error": "Object of type Items is not JSON serializable", "trace": "[FrameInfo(frame=<frame at 0x7fdbd3c40f40, file './routers/__init__.py', line 69, code custom_route_handler>, filename='./routers/__init__.py', lineno=45, function='custom_route_handler', code_context=['                response: Response = await original_route_handler(request)\\n'], index=0), FrameInfo(frame=<frame at 0x7fdbd5a7b470, file '/usr/local/lib/python3.8/site-packages/fastapi/routing.py', line 226, code app>, filename='/usr/local/lib/python3.8/site-packages/fastapi/routing.py', lineno=226, function='app', code_context=['            raw_response = await run_endpoint_function(\\n'], index=0), FrameInfo(frame=<frame at 0x10f5551f0, file '/usr/local/lib/python3.8/site-packages/fastapi/routing.py', line 161, code run_endpoint_function>, filename='/usr/local/lib/python3.8/site-packages/fastapi/routing.py', lineno=161, function='run_endpoint_function', code_context=['        return await run_in_threadpool(dependant.call, **values)\\n'], index=0), FrameInfo(frame=<frame at 0x10f550b20, file '/usr/local/lib/python3.8/site-packages/starlette/concurrency.py', line 40, code run_in_threadpool>, filename='/usr/local/lib/python3.8/site-packages/starlette/concurrency.py', lineno=40, function='run_in_threadpool', code_context=['    return await loop.run_in_executor(None, func, *args)\\n'], index=0), FrameInfo(frame=<frame at 0x10f559230, file '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py', line 63, code run>, filename='/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py', lineno=57, function='run', code_context=['            result = self.fn(*self.args, **self.kwargs)\\n'], index=0), FrameInfo(frame=<frame at 0x7fdbd5a7cf60, file './routers/payment.py', line 55, code payment_checkout>, filename='./routers/payment.py', lineno=55, function='payment_checkout', code_context=['    print(\"ARGSS-----> \",json.dumps(args))\\n'], index=0), FrameInfo(frame=<frame at 0x7fdbd5a7d1e0, file '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py', line 231, code dumps>, filename='/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py', lineno=231, function='dumps', code_context=['        return _default_encoder.encode(obj)\\n'], index=0), FrameInfo(frame=<frame at 0x10f552c80, file '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', line 199, code encode>, filename='/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', lineno=199, function='encode', code_context=['        chunks = self.iterencode(o, _one_shot=True)\\n'], index=0), FrameInfo(frame=<frame at 0x7fdbd5a7d410, file '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', line 257, code iterencode>, filename='/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', lineno=257, function='iterencode', code_context=['        return _iterencode(o, 0)\\n'], index=0), FrameInfo(frame=<frame at 0x10f420040, file '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', line 179, code default>, filename='/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', lineno=179, function='default', code_context=[\"        raise TypeError(f'Object of type {o.__class__.__name__} '\\n\"], index=0)]"}
Traceback (most recent call last):
  File "./routers/__init__.py", line 45, in custom_route_handler
    response: Response = await original_route_handler(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./routers/payment.py", line 55, in payment_checkout
    print("ARGSS-----> ",json.dumps(args))
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Items is not JSON serializable
[2021-11-25 23:53:27.422] ERROR [4492205504] - {"req_id": "DM9CCE20211125235327", "http_method": "POST", "url_path": "/payment/payment_checkout", "headers": [["host", "0.0.0.0:8888"], ["connection", "keep-alive"], ["content-length", "412"], ["accept", "application/json"], ["dnt", "1"], ["user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36"], ["content-type", "application/json"], ["origin", "http://0.0.0.0:8888"], ["referer", "http://0.0.0.0:8888/docs"], ["accept-encoding", "gzip, deflate"], ["accept-language", "en-US,en;q=0.9,id;q=0.8,ms;q=0.7"]], "query_param": [], "ip_forwarded": null, "ip_client_host": "127.0.0.1", "request_body": "{\n  \"invoice_no\": \"spaj/10202/1010\",\n  \"total_amount\": \"30000\",\n  \"customer\": {\n    \"custid\": \"CUST-0001\",\n    \"name\": \"Anton Budiman\",\n    \"email\": \"anton@example.com\",\n    \"phone\": \"6285694566147\",\n    \"address\": \"Menara Mulia Lantai 8\"\n  },\n  \"line_items\": [\n    {\n      \"name\": \"Asuransi\",\n      \"price\": \"30000\",\n      \"qty\": \"1\"\n    }\n  ],\n  \"paytype\": \"string\",\n  \"payvendor\": \"Doku\",\n  \"bank\": \"string\"\n}", "error": "Object of type Items is not JSON serializable", "trace": "[FrameInfo(frame=<frame at 0x7fd76f4d5890, file './routers/__init__.py', line 69, code custom_route_handler>, filename='./routers/__init__.py', lineno=45, function='custom_route_handler', code_context=['                response: Response = await original_route_handler(request)\\n'], index=0), FrameInfo(frame=<frame at 0x7fd771118450, file '/usr/local/lib/python3.8/site-packages/fastapi/routing.py', line 226, code app>, filename='/usr/local/lib/python3.8/site-packages/fastapi/routing.py', lineno=226, function='app', code_context=['            raw_response = await run_endpoint_function(\\n'], index=0), FrameInfo(frame=<frame at 0x10d1051f0, file '/usr/local/lib/python3.8/site-packages/fastapi/routing.py', line 161, code run_endpoint_function>, filename='/usr/local/lib/python3.8/site-packages/fastapi/routing.py', lineno=161, function='run_endpoint_function', code_context=['        return await run_in_threadpool(dependant.call, **values)\\n'], index=0), FrameInfo(frame=<frame at 0x10d100b20, file '/usr/local/lib/python3.8/site-packages/starlette/concurrency.py', line 40, code run_in_threadpool>, filename='/usr/local/lib/python3.8/site-packages/starlette/concurrency.py', lineno=40, function='run_in_threadpool', code_context=['    return await loop.run_in_executor(None, func, *args)\\n'], index=0), FrameInfo(frame=<frame at 0x10d109230, file '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py', line 63, code run>, filename='/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py', lineno=57, function='run', code_context=['            result = self.fn(*self.args, **self.kwargs)\\n'], index=0), FrameInfo(frame=<frame at 0x7fd7712f6930, file './routers/payment.py', line 57, code payment_checkout>, filename='./routers/payment.py', lineno=57, function='payment_checkout', code_context=['    digest = hlp.genDigest(json.dumps(args))\\n'], index=0), FrameInfo(frame=<frame at 0x7fd7712f6bb0, file '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py', line 231, code dumps>, filename='/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py', lineno=231, function='dumps', code_context=['        return _default_encoder.encode(obj)\\n'], index=0), FrameInfo(frame=<frame at 0x10d102c80, file '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', line 199, code encode>, filename='/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', lineno=199, function='encode', code_context=['        chunks = self.iterencode(o, _one_shot=True)\\n'], index=0), FrameInfo(frame=<frame at 0x7fd7712f6de0, file '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', line 257, code iterencode>, filename='/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', lineno=257, function='iterencode', code_context=['        return _iterencode(o, 0)\\n'], index=0), FrameInfo(frame=<frame at 0x10cfd0040, file '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', line 179, code default>, filename='/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py', lineno=179, function='default', code_context=[\"        raise TypeError(f'Object of type {o.__class__.__name__} '\\n\"], index=0)]"}
Traceback (most recent call last):
  File "./routers/__init__.py", line 45, in custom_route_handler
    response: Response = await original_route_handler(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./routers/payment.py", line 57, in payment_checkout
    digest = hlp.genDigest(json.dumps(args))
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Items is not JSON serializable
